### ISSUE TITLE
OCRopus4

### ISSUE THREAD

**Issue by mrocr** [tmbarchive/ocropus#1]
@tmbdev Hi there,
- Will it include new recognition techniques
- Will it include new text-line/paragraph segmentation methods
- Will it include export  and deployment options, int8, onnx then tensorrt, etc...

Alot have changed since ocropus3, the ocr field have gotten weirder:
[paragraph level recognition](https://github.com/FactoDeepLearning/VerticalAttentionOCR), [transformers](https://github.com/vlomme/OCR-transformer), [hybrid transformers](https://github.com/lolpa1n/digital-peter-ocrv), [classification](https://github.com/Media-Smart/vedastr) [and](https://arxiv.org/abs/2102.10884) [deployment](https://github.com/Media-Smart/volksdep), etc.....

**Comment by tmbdev** [comment]
OCRopus 4 is all-GPU models supporting multiple different recognition/segmentation strategies, as well as pre- and post-processing. The focus is on printed OCR (also, FAX, PDF, etc.).

OCRopus 4 is model-agnostic; you can plug in whatever models you can express in PyTorch and export the weights to whatever environment you want to.  You can plug in transformer-based models if you like, but for printed OCR, they don’t seem to provide good performance tradeoffs (they may be better for handwriting, but that’s not an objective of OCRopus 4). 

The deep learning architectures themselves really aren’t where the difficulties lie in OCR these days; the hard parts are mostly related to large scale data management, unbalanced training sets, unsupervised training, self-supervised training, language modeling, etc.

**Comment by mrocr** [comment]
Thank you

**Comment by mrocr** [comment]
@tmbdev 
Though i am curious, wouldn't an [x-height with borders](http://imagine.enpc.fr/~monniert/docExtractor/) method be suitable for both printed and handwritten documents, and is easy to implement?

Which approach are you going to use for text-line segmentation?

**Comment by tmbdev** [comment]
OCRopus4 implements the marker-plus-separator approach as described in the ICDAR 2019 tutorial:

https://github.com/tmbdev-tutorials/icdar2019-tutorial/blob/master/150-layout.ipynb

The "x-height with borders" method looks very similar.

This is based on the earlier generic page segmentation approach described here:

T. M. Breuel, "Robust, Simple Page Segmentation Using Hybrid Convolutional MDLSTM Networks," 2017 14th IAPR International Conference on Document Analysis and Recognition (ICDAR)

OCRopus4 generally uses MDLSTM in combination with convolutional layers because it works better than UNET alone, and it uses centerlines instead of x-height because that's more robust. But both the models and the ground truth are fully user configurable, so if you want to train "x-height with borders" or plain UNET, OCRopus4 supports that.

**Comment by mrocr** [comment]
@tmbdev How does your implementation perform against the following 8 images? [test.zip](https://github.com/tmbarchive/ocropus/files/6331981/test.zip)

**Comment by tmbdev** [comment]
Generally, the recognition code works for all sizes, paragraph shapes, and text orientations. Internally, all the training and recognition is done  in terms of bitmaps/arrays. So it really is just a question of models and training data.

We're still training the models for standard sizes and orientations. Later we'll train a second set of models for unusual sizes, orientations, and text line shapes (as in your samples).

**Comment by mrocr** [comment]
> Generally, the **recognition code**

Did you mean the **line detection** code? because detection is my aim.

- Can your implementation detect the curved text-line title? inwhich the markers and separators are curved. 
 i attached the image below.

![curve](https://user-images.githubusercontent.com/48284598/115295563-8e3a8980-a162-11eb-8521-343a38eab0cc.jpg)

**Comment by tmbdev** [comment]
The code can detect and segment curved text at any orientation. But we currently don't actually train models on curved text.

Do you have a training set of curved text data? If you do, it would be fairly easy to train on it. Otherwise, the plan is to train on artificially generated rotated text eventually.
